platform :ios, '8.0'

pod 'AFNetworking'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'MJExtension'
pod 'MWPhotoBrowser'
pod 'JSQMessagesViewController'
pod 'ZYQAssetPickerController'
pod 'MMDrawerController'